pipeline {
    agent {
        docker {
           image 'maven:3.5.4'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -Dmaven.repo.local=/Users/macos/.m2/repository/ -DskipTests clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
