pipeline {
    agent {         
       docker {          
         image 'maven:3.5.4'         
     }       
  }   
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                echo 'begin docker ps'
                sh 'docker ps'
                echo 'end docker ps'
                sh 'mvn -Dmaven.repo.local=/Users/macos/.m2/repository/ -DskipTests clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Dmaven.test.failure.ignore=true'
            }
            post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
